services:
  db:
    image: postgres:16
    container_name: capevents-postgres
    environment:
      POSTGRES_USER: capevents
      POSTGRES_PASSWORD: root
      POSTGRES_DB: capevents
    ports:
        - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: capevents-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  pgdata: