package com.capevents.backend.entity.enums;

public enum PointTransactionType {
    REGISTRATION_BONUS,
    UNREGISTER_PENALTY,
    ATTENDANCE_PRESENT_BONUS,
    ATTENDANCE_ABSENT_PENALTY,
    FEEDBACK_BONUS,
    EVENT_PROPOSAL_APPROVED_BONUS,

    REWARD_REDEMPTION_SPENT,
    REWARD_REDEMPTION_REFUND
}