server:
  port : 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/capevents
    username: capevents
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: USERNAME_MAILTRAP
    password: PASSWORD_MAILTRAP
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: dev

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  security:
    jwt:
      secret: "capgemini-pfe-dev-secret-key-very-long"
      access-expiration-minutes: 30
      refresh-expiration-days: 7
    allowed-email-domains:
      - capgemini.com
      - entreprise.local
      - test.com

  mail:
    from: noreply@capevents.local
    frontend-base-url: http://localhost:8080