spring:
  config:
    activate:
      on-profile: mailtrap

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 0214ca4c41461d
    password: cdd0170d5c9615
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true