package com.capevents.backend.notification;

public enum NotificationType {
    EVENT_INVITATION_RECEIVED,
    EVENT_REGISTRATION_CONFIRMED,
    EVENT_CANCELLED,
    EVENT_RESCHEDULED,

    EVENT_PROPOSAL_SUBMITTED,
    EVENT_PROPOSAL_PENDING_FOR_CREATOR,
    EVENT_PROPOSAL_APPROVED,
    EVENT_PROPOSAL_REJECTED,

    EVENT_PUBLISHED,
    EVENT_REMINDER_24H,
    REGISTRATION_DEADLINE_REMINDER,
    EVENT_FEEDBACK_AVAILABLE
}